import {
  GraduationCap,
  Briefcase,
  BookOpen,
  Bookmark,
  Code,
  Terminal,
  Compass,
  Layout,
  Sparkles,
  Folder,
  FolderOpen,
  FileText,
  Globe,
  Coffee,
  Heart,
  Music,
  Video,
  Database,
  Cpu,
  Feather,
  Flame,
  Zap,
  Rocket,
  Palette,
  Atom,
  Shield,
  Cloud,
  Radio,
  Package,
  Wrench,
  MessageSquare,
  Star,
  CheckSquare,
  Activity,
  Layers,
  Monitor,
  Smartphone,
  Search,
  Target,
  Anchor,
  LucideIcon
} from 'lucide-react';

export const FOLDER_ICONS: Record<string, LucideIcon> = {
  GraduationCap,
  Briefcase,
  BookOpen,
  Bookmark,
  Code,
  Terminal,
  Compass,
  Layout,
  Sparkles,
  Folder,
  FolderOpen,
  FileText,
  Globe,
  Coffee,
  Heart,
  Music,
  Video,
  Database,
  Cpu,
  Feather,
  Flame,
  Zap,
  Rocket,
  Palette,
  Atom,
  Shield,
  Cloud,
  Radio,
  Package,
  Wrench,
  MessageSquare,
  Star,
  CheckSquare,
  Activity,
  Layers,
  Monitor,
  Smartphone,
  Search,
  Target,
  Anchor,
};

export function getFolderIcon(name: string): LucideIcon {
  return FOLDER_ICONS[name] || Folder;
}

export const FOLDER_COLOR_MAP: Record<string, { bg: string; text: string; dot: string; border: string; darkBg: string; darkText: string }> = {
  forest: {
    bg: 'bg-emerald-50 dark:bg-emerald-950/40',
    text: 'text-emerald-800 dark:text-emerald-300',
    dot: 'bg-emerald-600 dark:bg-emerald-400',
    border: 'border-emerald-200 dark:border-emerald-800/60',
    darkBg: 'bg-emerald-900/30',
    darkText: 'text-emerald-300',
  },
  emerald: {
    bg: 'bg-teal-50 dark:bg-teal-950/40',
    text: 'text-teal-800 dark:text-teal-300',
    dot: 'bg-teal-600 dark:bg-teal-400',
    border: 'border-teal-200 dark:border-teal-800/60',
    darkBg: 'bg-teal-900/30',
    darkText: 'text-teal-300',
  },
  slate: {
    bg: 'bg-slate-100 dark:bg-slate-800/50',
    text: 'text-slate-700 dark:text-slate-300',
    dot: 'bg-slate-600 dark:bg-slate-400',
    border: 'border-slate-200 dark:border-slate-700',
    darkBg: 'bg-slate-800/40',
    darkText: 'text-slate-300',
  },
  amber: {
    bg: 'bg-amber-50 dark:bg-amber-950/40',
    text: 'text-amber-800 dark:text-amber-300',
    dot: 'bg-amber-600 dark:bg-amber-400',
    border: 'border-amber-200 dark:border-amber-800/60',
    darkBg: 'bg-amber-900/30',
    darkText: 'text-amber-300',
  },
  sky: {
    bg: 'bg-sky-50 dark:bg-sky-950/40',
    text: 'text-sky-800 dark:text-sky-300',
    dot: 'bg-sky-600 dark:bg-sky-400',
    border: 'border-sky-200 dark:border-sky-800/60',
    darkBg: 'bg-sky-900/30',
    darkText: 'text-sky-300',
  },
  indigo: {
    bg: 'bg-indigo-50 dark:bg-indigo-950/40',
    text: 'text-indigo-800 dark:text-indigo-300',
    dot: 'bg-indigo-600 dark:bg-indigo-400',
    border: 'border-indigo-200 dark:border-indigo-800/60',
    darkBg: 'bg-indigo-900/30',
    darkText: 'text-indigo-300',
  },
  rose: {
    bg: 'bg-rose-50 dark:bg-rose-950/40',
    text: 'text-rose-800 dark:text-rose-300',
    dot: 'bg-rose-600 dark:bg-rose-400',
    border: 'border-rose-200 dark:border-rose-800/60',
    darkBg: 'bg-rose-900/30',
    darkText: 'text-rose-300',
  },
  purple: {
    bg: 'bg-purple-50 dark:bg-purple-950/40',
    text: 'text-purple-800 dark:text-purple-300',
    dot: 'bg-purple-600 dark:bg-purple-400',
    border: 'border-purple-200 dark:border-purple-800/60',
    darkBg: 'bg-purple-900/30',
    darkText: 'text-purple-300',
  },
};
